pipeline {
    agent any
    
    stages {
        
        stage('github-clone') {
            steps {
                git branch: 'main', credentialsId: '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', url: 'https://github.com/Turtles24/blog_backend.git'
            }
        }
        
   		stage('Deploy') {
	        steps {
    	        sshagent(credentials: ['aws_key']) {
			        sh '''
            				ssh -o StrictHostKeyChecking=no ubuntu@13.124.106.142
                            scp /var/jenkins_home/workspace/DaonBlog-0.0.1-SNAPSHOT.jar ubuntu@13.124.106.142:/home/ubuntu/blog_backend
                            ssh -tt ubuntu@13.124.106.142 sh ./deploy.sh
                        '''
		            }
	            }
        }
   	}
}
